# 🐻‍❄️🎈 metrics-exporter-opentelemetry: metrics exporter over OpenTelemetry
# Copyright (c) 2025 Noelware, LLC. <team@noelware.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# The `rustfmt.toml` configuration file does use Nightly features, which
# is OK since we are pointed to a Nightly release (via `rust-toolchain.toml`),
#
# Consumers who are only building the project don't need a Nightly toolchain
# required unless distributors use Clippy / rustfmt to check if a project's
# structure is ok like `nixpkgs`.

### STABLE FEATURES
array_width = 90
max_width = 120
match_arm_leading_pipes = "Preserve"
newline_style = "Unix"
single_line_let_else_max_width = 0
use_field_init_shorthand = true
use_try_shorthand = true

### NIGHTLY FEATURES
binop_separator = "Back"
combine_control_expr = true
comment_width = 90
condense_wildcard_suffixes = true
group_imports = "One"
imports_granularity = "Crate"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
